# Generated by Django 3.0.5 on 2020-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the member', max_length=128)),
                ('position', models.CharField(max_length=36)),
                ('batch', models.IntegerField(help_text='expected pass-out year')),
                ('program', models.CharField(help_text='program ex:UG', max_length=64)),
                ('branch', models.CharField(help_text='branch', max_length=64)),
                ('about_me', models.CharField(help_text='Add something about You.', max_length=1536)),
                ('email', models.EmailField(blank=True, default=None, help_text='email address', max_length=254, null=True)),
                ('github_link', models.URLField(blank=True, default=None, help_text='Github link', null=True)),
                ('gitlab_link', models.URLField(blank=True, default=None, help_text='Gitlab link', null=True)),
                ('linkedIn_link', models.URLField(blank=True, default=None, help_text='linkedIn link', null=True)),
                ('website_link', models.URLField(blank=True, default=None, help_text='Website link', null=True)),
            ],
        ),
    ]
