# Generated by Django 3.0.5 on 2020-04-13 09:01

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of project', max_length=64)),
                ('cover', versatileimagefield.fields.VersatileImageField(upload_to='projects')),
                ('short_description', models.CharField(help_text='Short description of project', max_length=64)),
                ('description', models.TextField(help_text='Description of project')),
                ('technologies', models.CharField(help_text='Technologies to be used in the project', max_length=2048)),
                ('github_link', models.URLField(blank=True, default=None, null=True)),
                ('gitlab_link', models.URLField(blank=True, default=None, null=True)),
                ('website_link', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
