# Generated by Django 3.0.5 on 2020-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, default=None, help_text='Github link', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='gitlab_link',
            field=models.URLField(blank=True, default=None, help_text='Gitlab link', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, default=None, help_text='Website link', null=True),
        ),
    ]
