# Generated by Django 3.0.5 on 2020-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
                ('button1', models.CharField(blank=True, max_length=64)),
                ('button1link', models.URLField(blank=True, default=None, null=True)),
                ('button2', models.CharField(blank=True, max_length=64)),
                ('button2link', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
